### Define base URL
@base_url = http://127.0.0.1:8000/api



POST {{base_url}}/trip
Content-Type: application/json

{
  "session_id": "abc123",
  "fingerprint": "xyz789",
  "events": {
    "entered_freeway": [1.2345, -2.4567],
    "express_lanes": [
      {
        "name": "Lowell (WB)",
        "entered_at": [1.3214, -2.4666],
        "recommendation": true,
        "used": false
      }
    ],
    "exited_freeway": [1.3456, -2.5678]
  },
  "positions": [
    [1.1111, -1.1111],
    [2.2222, -2.2222],
    [3.3333, -3.3333],
    [4.4444, -4.4444]
  ]
}